Data
AliShah51215/calculator pull request #19
Opened 2021-09-25 00:16 UTC by AliShah51215

2021-09-25 07:45 UTC, MateuszMarczak commented
folder target nie powinien sie tutaj sie znalesc

2021-09-25 07:45 UTC, MateuszMarczak requested changes

2021-09-25 07:45 UTC, MateuszMarczak commented on pom.xml
> +  <artifactId>CreateTxtFile</artifactId>
Po co te zmiany tutaj?

2021-09-25 07:45 UTC, MateuszMarczak commented on src/main/java/data/Text/Main.java
> +        String pathToFile = "C:\\Users\\Ali\\IdeaProjects\\Github\\target\\data.txt";
w tym momencie u mnie to nie dziala. Przeczytaj prosze:
https://docs.oracle.com/javase/tutorial/essential/io/path.html

2021-09-25 07:45 UTC, MateuszMarczak commented on src/main/java/data/Text/Main.java
> +        }
jak juz to ten try catch powinien sie znaelsc w metodzie writeToFile

2021-09-26 12:11 UTC, mtszpater approved these changes

2021-09-26 12:12 UTC, mtszpater commented
Dałem approve, bo już coraz bliżej końca, ale posprzątaj proszę ten PR przed mergem. Masz kilka niepotrzebnych plików dodanych. Zerknij na tę zakładkę:

![image](https://user-images.githubusercontent.com/17989854/134807450-a4d20796-ffb6-421a-8ae2-e1c90c1f1ef1.png)

2021-09-27 16:05 UTC, merged